#…Ë÷√∂Àø⁄
server:
  port: 8088
#≈‰÷√ ˝æ›ø‚
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn
    username: root
    password: root
  application:
    name: dubbo-nacos-mp-provider
#≈‰÷√mybatis-plus
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#mybatis-plus:
  mapper-locations: classpath:mapper/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#≈‰÷√nacos
nacos:
  config:
    server-addr: localhost:8848
#≈‰÷√dubbo
dubbo:
  application:
    name: dubbo-nacos-mp-provider
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.whs.dubbonacosmybatisplusprovider
  protocol:
    name: dubbo
    port: 20881

